### ISSUE TITLE
Pizza: Favorite Food

### ISSUE THREAD

**Issue by nadine-amin** [wmustafaAwad/FirstGPTestRepo#3]
Not really sure but it was the first that came to my mind. What about you?

Also that was my last commit: b9251fd7089384ebf876d05f1aca6eaa2aa6b73f

@wmustafaAwad 
@AlaaHesham1996

**Comment by wmustafaAwad** [comment]
Well.. that's very critical. @Abdulhady-Feteiha , please solve and close when solved.

**Comment by TasneemOmara** [comment]
I found the right solution, please say 3ash to me @wmustafaAwad @Nadine-Amr @Abdulhady-Feteiha 
my last commit: 8ca4468
